cargopants = [
  {
    "id": 176,
    "title": "Polo Cargo Pants",
    "image": "static/images/cargopants/cargo2.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "United Colors of Benetton",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 177,
    "title": "Levi's Cargo Pants",
    "image": "static/images/cargopants/cargo3.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "Levi's",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 178,
    "title": "Buffalo Cargo Pants",
    "image": "static/images/cargopants/cargo4.png",
    "price": 16,
    "description": "Comfortable and stylish jeans.",
    "brand": "Buffalo",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 179,
    "title": "Allen Solly Cargo Pants",
    "image": "static/images/cargopants/cargo5.png",
    "price": 14,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 180,
    "title": "Arrow Cargo Pants",
    "image": "static/images/cargopants/cargo6.png",
    "price": 15,
    "description": "Comfortable and stylish jeans.",
    "brand": "Arrow",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 181,
    "title": "Polo Cargo Pants",
    "image": "static/images/cargopants/cargo7.png",
    "price": 21,
    "description": "Comfortable and stylish jeans.",
    "brand": "Polo",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 182,
    "title": "Polo Cargo Pants",
    "image": "static/images/cargopants/cargo8.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Polo",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 183,
    "title": "Allen Solly Cargo Pants",
    "image": "static/images/cargopants/cargo9.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 184,
    "title": "Mango Cargo Pants",
    "image": "static/images/cargopants/cargo10.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Mango",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 185,
    "title": "Arrow Cargo Pants",
    "image": "static/images/cargopants/cargo11.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Arrow",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 186,
    "title": "Allen Solly Cargo Pants",
    "image": "static/images/cargopants/cargo1.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 197,
    "title": "United Colours of Benetton Cargo Pants",
    "image": "static/images/cargopants/cargo12.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "United Colors of Benetton",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  }
]