jackets = [
  {
    "id": 198,
    "title": "Peter England Jacket",
    "image": "static/images/jackets/jacket1.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "Peter England",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 199,
    "title": "Puma Jacket",
    "image": "static/images/jackets/jacket2.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "Puma",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 201,
    "title": "Levi's Jacket",
    "image": "static/images/jackets/jacket3.png",
    "price": 16,
    "description": "Comfortable and stylish jeans.",
    "brand": "Levi's",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 202,
    "title": "Allen Solly Jacket",
    "image": "static/images/jackets/jacket4.png",
    "price": 14,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 203,
    "title": "Wrangler Jacket",
    "image": "static/images/jackets/jacket5.png",
    "price": 15,
    "description": "Comfortable and stylish jeans.",
    "brand": "Wrangler",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 204,
    "title": "Looney Jacket",
    "image": "static/images/jackets/jacket6.png",
    "price": 21,
    "description": "Comfortable and stylish jeans.",
    "brand": "Looney",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 205,
    "title": "H&M Jacket",
    "image": "static/images/jackets/jacket7.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "H&M",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 206,
    "title": "Mufti Jacket",
    "image": "static/images/jackets/jacket8.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Mufti",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 207,
    "title": "Woodland Jacket",
    "image": "static/images/jackets/jacket9.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Woodland",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  },
  {
    "id": 208,
    "title": "Spykar Jacket",
    "image": "static/images/jackets/jacket10.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Sypkar",
    "model": "501",
    "color": "Blue",
    "category": "Jacket",
    "popular": True,
    "discount": 2
  }
]