jeans = [
  {
    "id": 165,
    "title": "United Colours of Benetton Jeans",
    "image": "static/images/jeans/jeans2.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "United Colors of Benetton",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 166,
    "title": "Levi's Jeans",
    "image": "static/images/jeans/jeans3.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "Levi's",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 167,
    "title": "Buffalo Jeans",
    "image": "static/images/jeans/jeans4.png",
    "price": 16,
    "description": "Comfortable and stylish jeans.",
    "brand": "Buffalo",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 168,
    "title": "Allen Solly Jeans",
    "image": "static/images/jeans/jeans5.png",
    "price": 14,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 169,
    "title": "Arrow Jeans",
    "image": "static/images/jeans/jeans6.png",
    "price": 15,
    "description": "Comfortable and stylish jeans.",
    "brand": "Arrow",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 170,
    "title": "Polo Jeans",
    "image": "static/images/jeans/jeans7.png",
    "price": 21,
    "description": "Comfortable and stylish jeans.",
    "brand": "Polo",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 171,
    "title": "Polo Jeans",
    "image": "static/images/jeans/jeans8.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Polo",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 172,
    "title": "Allen Solly Jeans",
    "image": "static/images/jeans/jeans9.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 173,
    "title": "Mango Jeans",
    "image": "static/images/jeans/jeans10.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Mango",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 174,
    "title": "Arrow Jeans",
    "image": "static/images/jeans/jeans11.png",
    "price": 20,
    "description": "Comfortable and stylish jeans.",
    "brand": "Arrow",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  },
  {
    "id": 175,
    "title": "Allen Solly Jeans",
    "image": "static/images/jeans/jeans1.png",
    "price": 19,
    "description": "Comfortable and stylish jeans.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Jeans",
    "popular": True,
    "discount": 2
  }
]