shirts = [
  {
    "id": 158,
    "title": "Mango Shirt",
    "image": "static/images/shirts/shirt1.png",
    "price": 19,
    "description": "Comfortable and stylish shirt.",
    "brand": "Mango",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
  {
    "id": 159,
    "title": "Arrow Shirt",
    "image": "static/images/shirts/shirt2.png",
    "price": 19,
    "description": "Comfortable and stylish shirt.",
    "brand": "Arrow",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
  {
    "id": 160,
    "title": "Levi's Shirt",
    "image": "static/images/shirts/shirt3.png",
    "price": 16,
    "description": "Comfortable and stylish shirt.",
    "brand": "Levi's",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
  {
    "id": 161,
    "title": "Van Heusen Shirt",
    "image": "static/images/shirts/shirt4.png",
    "price": 14,
    "description": "Comfortable and stylish shirt.",
    "brand": "Van Heusen",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
  {
    "id": 162,
    "title": "Allen Solly Shirt",
    "image": "static/images/shirts/shirt5.png",
    "price": 15,
    "description": "Comfortable and stylish shirt.",
    "brand": "Allen Solly",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
  {
    "id": 163,
    "title": "United Colours of Benetton Shirt",
    "image": "static/images/shirts/shirt6.png",
    "price": 21,
    "description": "Comfortable and stylish shirt.",
    "brand": "United Colors of Benetton",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
  {
    "id": 164,
    "title": "Polo Shirt",
    "image": "static/images/shirts/shirt7.png",
    "price": 20,
    "description": "Comfortable and stylish shirt.",
    "brand": "Polo",
    "model": "501",
    "color": "Blue",
    "category": "Shirts",
    "popular": True,
    "discount": 2
  },
]